---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomline
  labels:
    app.kubernetes.io/name: randomline
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: randomline
  template:
    metadata:
      labels:
        app.kubernetes.io/name: randomline
    spec:
      containers:
        - name: randomline
          image: randomline
          env:
            - name: GOWON_BROKER
              value: mosquitto:1883
